DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS user_login;
DROP TABLE IF EXISTS email_confirmation_queue;
DROP TABLE IF EXISTS booking_log;
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS users;
